version: '3'
services:
  # define the wordpress container
  wordpress_container:
    image: wordpress
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_HOST=mysql_container
    depends_on:
      - mysql_container
  # define the myswl container
  mysql_container:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
  # define the nginx-container
  loadbalancer-nginx:
    image: nginx
    
  
networks:
  # define the networks


